// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.7
// source: proto/config/text.proto

package config

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 写入的请求
type TextWriteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path    string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`       // 路径
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // 内容
}

func (x *TextWriteRequest) Reset() {
	*x = TextWriteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_config_text_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextWriteRequest) ProtoMessage() {}

func (x *TextWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_text_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextWriteRequest.ProtoReflect.Descriptor instead.
func (*TextWriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_text_proto_rawDescGZIP(), []int{0}
}

func (x *TextWriteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TextWriteRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 读取的请求
type TextReadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // 路径
}

func (x *TextReadRequest) Reset() {
	*x = TextReadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_config_text_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextReadRequest) ProtoMessage() {}

func (x *TextReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_text_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextReadRequest.ProtoReflect.Descriptor instead.
func (*TextReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_text_proto_rawDescGZIP(), []int{1}
}

func (x *TextReadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// 读取的回复
type TextReadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 回复的状态
	Entity *TextEntity `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"` // 文本的实体
}

func (x *TextReadResponse) Reset() {
	*x = TextReadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_config_text_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextReadResponse) ProtoMessage() {}

func (x *TextReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_text_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextReadResponse.ProtoReflect.Descriptor instead.
func (*TextReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_text_proto_rawDescGZIP(), []int{2}
}

func (x *TextReadResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *TextReadResponse) GetEntity() *TextEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

// 删除的请求
type TextDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *TextDeleteRequest) Reset() {
	*x = TextDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_config_text_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextDeleteRequest) ProtoMessage() {}

func (x *TextDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_text_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextDeleteRequest.ProtoReflect.Descriptor instead.
func (*TextDeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_text_proto_rawDescGZIP(), []int{3}
}

func (x *TextDeleteRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// 获取的请求
type TextGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *TextGetRequest) Reset() {
	*x = TextGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_config_text_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextGetRequest) ProtoMessage() {}

func (x *TextGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_text_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextGetRequest.ProtoReflect.Descriptor instead.
func (*TextGetRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_text_proto_rawDescGZIP(), []int{4}
}

func (x *TextGetRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// 获取的回复
type TextGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status     `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 回复的状态
	Entity *TextEntity `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"` // 文本的实体
}

func (x *TextGetResponse) Reset() {
	*x = TextGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_config_text_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextGetResponse) ProtoMessage() {}

func (x *TextGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_text_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextGetResponse.ProtoReflect.Descriptor instead.
func (*TextGetResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_text_proto_rawDescGZIP(), []int{5}
}

func (x *TextGetResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *TextGetResponse) GetEntity() *TextEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

// 列举的请求
type TextListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Offset int64 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count  int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *TextListRequest) Reset() {
	*x = TextListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_config_text_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextListRequest) ProtoMessage() {}

func (x *TextListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_text_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextListRequest.ProtoReflect.Descriptor instead.
func (*TextListRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_text_proto_rawDescGZIP(), []int{6}
}

func (x *TextListRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *TextListRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 列举的回复
type TextListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 回复的状态
	Entity []*TextEntity `protobuf:"bytes,2,rep,name=entity,proto3" json:"entity,omitempty"` // 文本的实体
}

func (x *TextListResponse) Reset() {
	*x = TextListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_config_text_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextListResponse) ProtoMessage() {}

func (x *TextListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_text_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextListResponse.ProtoReflect.Descriptor instead.
func (*TextListResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_text_proto_rawDescGZIP(), []int{7}
}

func (x *TextListResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *TextListResponse) GetEntity() []*TextEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

// 搜索的请求
type TextSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"` // 路径
}

func (x *TextSearchRequest) Reset() {
	*x = TextSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_config_text_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextSearchRequest) ProtoMessage() {}

func (x *TextSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_text_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextSearchRequest.ProtoReflect.Descriptor instead.
func (*TextSearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_config_text_proto_rawDescGZIP(), []int{8}
}

func (x *TextSearchRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// 搜索的回复
type TextSearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *Status       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // 回复的状态
	Entity []*TextEntity `protobuf:"bytes,2,rep,name=entity,proto3" json:"entity,omitempty"` // 文本的实体
}

func (x *TextSearchResponse) Reset() {
	*x = TextSearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_config_text_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextSearchResponse) ProtoMessage() {}

func (x *TextSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_config_text_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextSearchResponse.ProtoReflect.Descriptor instead.
func (*TextSearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_config_text_proto_rawDescGZIP(), []int{9}
}

func (x *TextSearchResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *TextSearchResponse) GetEntity() []*TextEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

var File_proto_config_text_proto protoreflect.FileDescriptor

var file_proto_config_text_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x74,
	0x65, 0x78, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x10, 0x54, 0x65, 0x78, 0x74, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x25, 0x0a, 0x0f, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x58, 0x0a,
	0x10, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x23, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52,
	0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x27, 0x0a, 0x11, 0x54, 0x65, 0x78, 0x74, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x22, 0x24, 0x0a, 0x0e, 0x54, 0x65, 0x78, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x57, 0x0a, 0x0f, 0x54, 0x65, 0x78, 0x74, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x0a, 0x06, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x54, 0x65, 0x78,
	0x74, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22,
	0x3f, 0x0a, 0x0f, 0x54, 0x65, 0x78, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x58, 0x0a, 0x10, 0x54, 0x65, 0x78, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x45, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x27, 0x0a, 0x11, 0x54, 0x65,
	0x78, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x22, 0x5a, 0x0a, 0x12, 0x54, 0x65, 0x78, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x0a, 0x06, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x54, 0x65, 0x78,
	0x74, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x32,
	0xa1, 0x02, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x12, 0x2b, 0x0a, 0x05, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x12, 0x11, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x57, 0x72, 0x69, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x55, 0x75, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64, 0x12, 0x10, 0x2e,
	0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x11, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x12,
	0x2e, 0x54, 0x65, 0x78, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x55, 0x75, 0x69, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0f, 0x2e, 0x54, 0x65, 0x78,
	0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x54, 0x65,
	0x78, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x2d, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x54, 0x65, 0x78, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x33,
	0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x12, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x54,
	0x65, 0x78, 0x74, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x15, 0x5a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x3b, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_config_text_proto_rawDescOnce sync.Once
	file_proto_config_text_proto_rawDescData = file_proto_config_text_proto_rawDesc
)

func file_proto_config_text_proto_rawDescGZIP() []byte {
	file_proto_config_text_proto_rawDescOnce.Do(func() {
		file_proto_config_text_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_config_text_proto_rawDescData)
	})
	return file_proto_config_text_proto_rawDescData
}

var file_proto_config_text_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_config_text_proto_goTypes = []interface{}{
	(*TextWriteRequest)(nil),   // 0: TextWriteRequest
	(*TextReadRequest)(nil),    // 1: TextReadRequest
	(*TextReadResponse)(nil),   // 2: TextReadResponse
	(*TextDeleteRequest)(nil),  // 3: TextDeleteRequest
	(*TextGetRequest)(nil),     // 4: TextGetRequest
	(*TextGetResponse)(nil),    // 5: TextGetResponse
	(*TextListRequest)(nil),    // 6: TextListRequest
	(*TextListResponse)(nil),   // 7: TextListResponse
	(*TextSearchRequest)(nil),  // 8: TextSearchRequest
	(*TextSearchResponse)(nil), // 9: TextSearchResponse
	(*Status)(nil),             // 10: Status
	(*TextEntity)(nil),         // 11: TextEntity
	(*UuidResponse)(nil),       // 12: UuidResponse
}
var file_proto_config_text_proto_depIdxs = []int32{
	10, // 0: TextReadResponse.status:type_name -> Status
	11, // 1: TextReadResponse.entity:type_name -> TextEntity
	10, // 2: TextGetResponse.status:type_name -> Status
	11, // 3: TextGetResponse.entity:type_name -> TextEntity
	10, // 4: TextListResponse.status:type_name -> Status
	11, // 5: TextListResponse.entity:type_name -> TextEntity
	10, // 6: TextSearchResponse.status:type_name -> Status
	11, // 7: TextSearchResponse.entity:type_name -> TextEntity
	0,  // 8: Text.Write:input_type -> TextWriteRequest
	1,  // 9: Text.Read:input_type -> TextReadRequest
	3,  // 10: Text.Delete:input_type -> TextDeleteRequest
	4,  // 11: Text.Get:input_type -> TextGetRequest
	6,  // 12: Text.List:input_type -> TextListRequest
	8,  // 13: Text.Search:input_type -> TextSearchRequest
	12, // 14: Text.Write:output_type -> UuidResponse
	2,  // 15: Text.Read:output_type -> TextReadResponse
	12, // 16: Text.Delete:output_type -> UuidResponse
	5,  // 17: Text.Get:output_type -> TextGetResponse
	7,  // 18: Text.List:output_type -> TextListResponse
	9,  // 19: Text.Search:output_type -> TextSearchResponse
	14, // [14:20] is the sub-list for method output_type
	8,  // [8:14] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_config_text_proto_init() }
func file_proto_config_text_proto_init() {
	if File_proto_config_text_proto != nil {
		return
	}
	file_proto_config_shared_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_config_text_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextWriteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_config_text_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextReadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_config_text_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextReadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_config_text_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_config_text_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_config_text_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_config_text_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_config_text_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_config_text_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_config_text_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextSearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_config_text_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_config_text_proto_goTypes,
		DependencyIndexes: file_proto_config_text_proto_depIdxs,
		MessageInfos:      file_proto_config_text_proto_msgTypes,
	}.Build()
	File_proto_config_text_proto = out.File
	file_proto_config_text_proto_rawDesc = nil
	file_proto_config_text_proto_goTypes = nil
	file_proto_config_text_proto_depIdxs = nil
}
